# Generated by Django 5.0.2 on 2024-06-01 21:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hudud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='QurilishTashkiloti',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('qachon_tashkil_topgan', models.DateField()),
                ('hudud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.hudud')),
            ],
        ),
        migrations.CreateModel(
            name='QurilishBinisi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('maydoni', models.DecimalField(decimal_places=2, max_digits=10)),
                ('qavat', models.IntegerField()),
                ('parkovka', models.BooleanField(default=False)),
                ('bolalar_maydonchasi', models.BooleanField(default=False)),
                ('lift', models.BooleanField(default=False)),
                ('hudud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.hudud')),
                ('qurilish_tashkiloti', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.qurilishtashkiloti')),
            ],
        ),
    ]
